"""
Script to generate comprehensive Architecture Knowledge, Mental Models, Data Flows,
Mind Maps, and Feature Deep-Dives for Project ANUMAAN (DRDO / SIH PS-26054).
Outputs to final_touch/ and final touch/ directories.
"""

import os
import shutil
from pathlib import Path

WORKSPACE = Path("e:/backup-llm/backup-no-llm/3d_engine").resolve()
FINAL_TOUCH = WORKSPACE / "final_touch"
FINAL_TOUCH_SPACE = WORKSPACE / "final touch"

FINAL_TOUCH.mkdir(parents=True, exist_ok=True)
FINAL_TOUCH_SPACE.mkdir(parents=True, exist_ok=True)

# -------------------------------------------------------------------------------------------------
# 1. SYSTEM ARCHITECTURE AND MENTAL MODELS
# -------------------------------------------------------------------------------------------------
DOC_1_CONTENT = """# ANUMAAN — System Architecture & Core Mental Models
**DRDO / SIH Problem Statement ID: 26054**
*AI-Enabled Real-Time Digital Twin System for Health Monitoring, Fault Prediction and Mission Reliability Enhancement of Aero Piston Engines used in MALE UAVs*

---

## Part I: The Seven Fundamental Mental Models

To understand, debug, or extend the ANUMAAN codebase, an engineer or researcher must abandon naive assumptions about "digital twins" and reason through the following seven core mental models:

```mermaid
graph TD
    subgraph MM["The 7 Core Mental Models of Project ANUMAAN"]
        M1["1. Truth vs. Observation Duality<br/>(VirtualEngine vs Frame vs TruthRecord)"]
        M2["2. Dual-Runtime Concurrency<br/>(Modern Multi-Engine Hub vs Legacy Rotax GCS)"]
        M3["3. OSA-CBM 6-Layer Hierarchy<br/>(ISO 13374 Condition-Based Maintenance)"]
        M4["4. Deterministic vs Probabilistic AI<br/>(ATA Diagnostic Agent vs Conformal RUL vs LLM)"]
        M5["5. Telemetry Rate Dichotomy<br/>(20 Hz Scalar Frame vs High-Rate Waveform DSP)"]
        M6["6. Physics vs Presentation Duality<br/>(Thermodynamic Math vs Three.js/Blender 3D Mesh)"]
        M7["7. Airframe vs Fleet Swarm Intelligence<br/>(Local Edge Twin vs FedNeMo Federated PHM)"]
    end
```

---

### Mental Model 1: The Truth vs. Observation Duality (`VirtualEngine` vs. `Frame` vs. `TruthRecord`)

In flawed digital twin architectures, the "simulated sensor values" are generated by taking the twin's own internal mathematical equations, adding Gaussian white noise, and adding an artificial offset when a fault is toggled. When the digital twin evaluates the incoming telemetry, it compares the data against the exact same equations that created it. Under such an arrangement, the residual is always identically zero (plus noise), any simple threshold detects the fault, and reported accuracy figures are completely deceptive.

**In ANUMAAN, this problem is solved by establishing an unbreachable wall between Plant and Twin:**

```mermaid
flowchart LR
    subgraph Plant["Physical Reality / VirtualEngine (backend/plant/)"]
        direction TB
        EVar["Engine Variation<br/>(Friction, Heat Scale, Volumetric Eff)"]
        SensModel["Sensor Dynamics<br/>(Bias Drift, Thermal Lag, Quantization)"]
        FaultInj["Hidden Fault Injection<br/>(Coking, Needle Stick, Oil Leak)"]
        PhysPlant["Higher-Fidelity Physics<br/>(Crank Dynamics, Turbo, Non-linear Oil)"]
        EVar --> PhysPlant
        SensModel --> PhysPlant
        FaultInj --> PhysPlant
    end

    subgraph Seam["The Unbreachable Architectural Seam"]
        Frame["Frame (backend/core/frame.py)<br/>PUBLIC TELEMETRY ONLY<br/>(RPM, MAP, CHT, EGT, Oil P, Volts)<br/>⚠️ Zero Fault Labels<br/>⚠️ Zero Health Indices<br/>⚠️ Zero RUL Values"]
        Truth["TruthRecord<br/>ISOLATED EVALUATION HARNESS<br/>(Ground Truth Fault ID, Active Severity,<br/>True Wear Parameters, Failure Time)"]
    end

    subgraph Twin["Digital Twin Intelligence (backend/detect/ & ml/)"]
        direction TB
        Resid["Residual Detector (Tier 0)<br/>Frame - Expected Baseline"]
        Classif["Classifier / Reservoir (Tier 1)<br/>Multi-channel Residual Pattern"]
    end

    PhysPlant -->|Produces| Frame
    PhysPlant -->|Evaluator Only| Truth
    Frame -->|Input to| Resid
    Resid -->|Triggers| Classif
    Truth -.->|Used ONLY in offline benchmark tests| Benchmark["Evaluation Harness<br/>(backend/evaluation/)"]
```

#### Key Architectural Invariants:
1. **Model Mismatch is Real:** Because `VirtualEngine` includes manufacturing tolerances, thermal inertia, and sensor lag that the twin's observer model does not know, the nominal residuals are **non-zero and structured**.
2. **Zero Label Leakage:** The `Frame` contract strictly forbids passing `FAULT_ID`, `HEALTH_INDEX`, or `RUL_HOURS`. The detector must infer anomalies purely from sensor residuals without prior knowledge.
3. **`TruthRecord` Isolation:** The ground truth is written to a distinct stream accessible solely by the automated test suite in `tests/` and benchmarks in `backend/evaluation/`.

---

### Mental Model 2: The Concurrent Dual-Runtime Architecture

The ANUMAAN backend hosts two distinct, parallel operational runtime stacks within the same FastAPI process. Understanding which pipeline serves which consumer is essential:

```mermaid
graph TB
    subgraph ClientLayer["Ground Control Station & Visualization Clients"]
        Console["Modern React Console<br/>(Default: Selected Engine + Fleet)"]
        LegacyGCS["Legacy React GCS Views<br/>(Rotax 912 iS Single-Engine)"]
        BlenderTwin["Blender EEVEE 3D Viewport<br/>(Native Python Socket Client)"]
        WebGLTwin["Three.js WebGL Engine Viewer<br/>(Embedded iframe in React)"]
    end

    subgraph ServerLayer["FastAPI Gateway (backend/server/main.py)"]
        FastAPI["FastAPI App (Port 8000)"]
        EngineAPI["Modern Engine Router<br/>(backend/server/engine_api.py)"]
        LegacyRouter["Legacy Telemetry Router<br/>(backend/server/main.py endpoints)"]
    end

    subgraph RuntimeLayer["Execution Engines"]
        Hub["RuntimeHub (backend/runtime/hub.py)<br/>• 20 Hz wall clock (1 sim-sec/tick)<br/>• Background auto-calibration<br/>• Concurrent multi-engine instances"]
        LegacySvc["EngineStateService (backend/server/engine_service.py)<br/>• Rotax 912 iS Singleton<br/>• Synthetic TelemetryStreamer<br/>• In-process ATA Diagnostic Agent"]
    end

    subgraph Engines["Configured Engine Profiles (configs/engines/)"]
        E1["Rotax 912 iS"]
        E2["Rotax 914 Turbo"]
        E3["Rotax 915 iS Turbo"]
        E4["Austro AE300 Diesel"]
        E5["VRDE Jayem 2.2L Diesel"]
    end

    FastAPI --> EngineAPI
    FastAPI --> LegacyRouter

    EngineAPI --> Hub
    LegacyRouter --> LegacySvc

    Hub --> Engines

    Console -->|HTTP & /ws/engines/id & /ws/fleet| EngineAPI
    WebGLTwin -->|GET /api/engines/id/state| EngineAPI
    LegacyGCS -->|HTTP & /ws/telemetry| LegacyRouter
    BlenderTwin -->|TCP Socket / REST /ws/telemetry| LegacyRouter
```

#### Runtime Comparison:
| Attribute | Modern Multi-Engine Runtime | Legacy Ground-Control Stack |
|---|---|---|
| **Entry Point** | `backend/server/engine_api.py` | `backend/server/main.py` + `engine_service.py` |
| **Engine Support** | Multi-engine (Rotax 912/914/915, Austro AE300, VRDE Jayem) | Rotax 912 iS only |
| **Clock Model** | Accelerated (20 ticks/sec, each tick = 1 sim-sec) | Real-time 20 Hz wall-clock streamer |
| **Detection Scheme**| Tier 0 `ResidualDetector` + Tier 1 `Reservoir` | Heuristic rules + Multi-class neural network |
| **Primary Client** | React `EngineRuntimeConsole` (default UI) | Legacy GCS role views & Blender desktop app |

---

### Mental Model 3: The OSA-CBM / ISO 13374 Six-Layer Architecture

ANUMAAN is architected directly against the international standard for Condition-Based Maintenance (**ISO 13374 / OSA-CBM**), mapped across six logical processing layers (`backend/osacbm.py`):

```mermaid
flowchart TD
    L1["Layer 1: Data Acquisition (DA)<br/>• Physical/Virtual CAN-bus Ingest (20 Hz)<br/>• High-rate Crank Tooth Sensors (≤ 25 ns timestamps)<br/>• Sensor Quality Bitmasks (stale, frozen, out-of-range)"]
    
    L2["Layer 2: Data Manipulation (DM)<br/>• Thermodynamic density derating (ICAO Standard Atmosphere)<br/>• Crank-angle domain transformation (0° to 720° cycle)<br/>• FFT Vibration Decomposition & Spectral Harmonics"]
    
    L3["Layer 3: State Detection (SD)<br/>• 13-feature Tail Calibration Residuals (TailCalibration.z)<br/>• FlyBloom LSH novelty scoring & Mahalanobis distance<br/>• Persistence Gating (3 of last 5 frames above conformal threshold)"]
    
    L4["Layer 4: Health Assessment (HA)<br/>• Multi-class Fault Classifier (DRDO 8 fault categories)<br/>• Inter-cylinder thermal & combustion imbalance metrics<br/>• Root-cause component localization (Mesh Locator)"]
    
    L5["Layer 5: Prognostic Assessment (PA)<br/>• Split-Conformal RUL prediction with 95% statistical coverage<br/>• Arrhenius thermal degradation & Miner's cumulative fatigue<br/>• Computed Mission Completion Reliability (Rm)"]
    
    L6["Layer 6: Advisory Generation (AG)<br/>• Deterministic ATA-Chapter Directives (ATA 72-79)<br/>• 4-Step Pilot Emergency Procedures<br/>• Depot-level Ground Crew Maintenance Work Orders"]

    L1 --> L2 --> L3 --> L4 --> L5 --> L6
```

---

### Mental Model 4: Deterministic Safety vs. Probabilistic Reasoning vs. RAG Copilot

A cornerstone design decision in ANUMAAN is the strict separation between safety-critical avionics logic and probabilistic artificial intelligence:

```mermaid
graph TD
    subgraph FlightCritical["Plane 1: Deterministic Safety Plane (Zero Hallucination)"]
        DetRules["Deterministic ATA Diagnostic Agent<br/>(backend/agent/diagnostic_agent.py)<br/>• Hard-coded expert knowledge base from Rotax MM<br/>• Strict 1-to-1 mapping: Fault Signature → ATA Chapter<br/>• Mandatory 4-step emergency checklists<br/>• Certified for airworthiness review"]
    end

    subgraph StatML["Plane 2: Statistically Bound Machine Learning"]
        ConfML["Conformal Prediction & PHM Models<br/>(backend/detect/ & backend/evaluation/)<br/>• Split-conformal calibration on held-out nominal data<br/>• Mathematically guaranteed false-alarm bound (alpha ≤ 0.01)<br/>• 95% confidence intervals on RUL hours"]
    end

    subgraph AssistiveAI["Plane 3: Conversational Copilot & Assistance (Advisory Only)"]
        RAGCopilot["Local LLM + Offline RAG<br/>(backend/agent/copilot.py & backend/knowledge/)<br/>• Local inference (Sarvam-30B, BharatGen, Qwen)<br/>• Vector search over offline technical PDF manuals<br/>• Local Whisper STT & Kokoro TTS voice synthesis<br/>⚠️ Strictly air-gapped; never issues flight commands"]
    end

    SensorData["Telemetry Frame"] --> DetRules
    SensorData --> StatML
    DetRules --> GCS["Ground Control Display"]
    StatML --> GCS
    UserQuery["Pilot / Engineer Voice Query"] --> RAGCopilot
    RAGCopilot --> AudioResponse["Synthesized Audio Briefing"]
```

---

### Mental Model 5: Telemetry Rate Dichotomy (Scalar 20 Hz vs. High-Rate Waveform DSP)

Engine physical degradation manifests across two distinct temporal scales. A diagnostic system that only reads scalar telemetry is blind to combustion dynamics, while a system that only processes waveforms drowns in computational complexity:

```mermaid
graph LR
    subgraph LowRate["Low-Rate Domain (20 Hz / 50 ms) — Frame"]
        direction TB
        Scalars["Scalar Telemetry:<br/>• CHT (4 cylinders)<br/>• EGT (4 cylinders)<br/>• Oil Pressure & Temperature<br/>• Fuel Rail Pressure & Mass Flow<br/>• Bus Voltage & Battery Current<br/>• Manifold Absolute Pressure (MAP)"]
        LRObs["Observable Failure Modes:<br/>• Severe Cooling Blockage (CHT runaway)<br/>• Total Oil Pressure Loss<br/>• Turbocharger Wastegate Stuck Open<br/>• Alternator Belt Failure / Voltage Sag<br/>• Sensor Bias Drift & Stuck Readings"]
        Scalars --> LRObs
    end

    subgraph HighRate["High-Rate Domain (10 kHz - 100 kHz) — CycleBlock"]
        direction TB
        Waveforms["Waveform Dynamics:<br/>• Crankshaft 60-2 tooth timestamps (≤ 25 ns)<br/>• In-cylinder pressure transients<br/>• Gearbox accelerometer vibration (kHz)<br/>• Fuel rail acoustic pressure pulses<br/>• Alternator bridge-rectifier ripple"]
        HRObs["Observable Failure Modes:<br/>• Early Injector Coking & Partial Orifice Clog<br/>• Needle Valve Bounce & Seat Sticking<br/>• Incipient Knock / Detonation<br/>• Indicated Mean Effective Pressure (IMEP) Imbalance<br/>• Planetary Gearbox Tooth Pitting & Bearing Fatigue"]
        Waveforms --> HRObs
    end
```

---

### Mental Model 6: Presentation vs. Physics Duality

The 3D engines in ANUMAAN (Blender EEVEE and Three.js WebGL) are visualization interfaces, not physics solvers:

```mermaid
sequenceDiagram
    participant P as Thermodynamic Plant (VirtualEngine)
    participant D as Residual Detector (Tier 0)
    participant A as ATA Diagnostic Agent
    participant S as FastAPI WebSocket Server
    participant UI as Three.js WebGL / Blender EEVEE

    P->>D: Telemetry Frame (No labels)
    D->>D: Detects CHT_2 residual spike (> 135°C)
    D->>A: Triggers Anomaly on Cyl #2
    A->>S: Emits Directive: Target Mesh = 'Covers_Theme_M_PlasticTheme_0'
    S->>UI: Transmits State JSON: {temp_cyl2: 138.4, highlight_mesh: 'Covers_Theme_M...'}
    Note over UI: UI adjusts shader color: Normal Metallic -> Glowing Crimson (255, 30, 0)<br/>Camera eases smoothly to Cylinder #2 inspection angle
```

---

### Mental Model 7: Single-Airframe Twin vs. Squadron Swarm Fleet Intelligence (`FedNeMo`)

Project ANUMAAN is designed not merely for a single prototype UAV on a testbench, but for operational squadrons of Medium Altitude Long Endurance UAVs (e.g. TAPAS-BH-201 / Rustom-II fleet) deployed across dispersed military bases:

```mermaid
graph TB
    subgraph Airbase1["Forward Operating Base Alpha (Ladakh Sector)"]
        UAV1["UAV Tail #01 (TAPAS-BH-201)<br/>Rotax 912 iS Engine"]
        UAV2["UAV Tail #02 (TAPAS-BH-201)<br/>Rotax 914 Turbo"]
        LocalClient1["FedNeMo Local Client<br/>• Reads sortie telemetry<br/>• Local gradient update<br/>• Differential Privacy (DP) Noise Addition<br/>• 8-bit Model Quantization"]
        UAV1 --> LocalClient1
        UAV2 --> LocalClient1
    end

    subgraph Airbase2["Forward Operating Base Bravo (South Sector)"]
        UAV3["UAV Tail #03 (TAPAS-BH-201)<br/>Austro AE300 Diesel"]
        LocalClient2["FedNeMo Local Client<br/>• Reads sortie telemetry<br/>• Local gradient update<br/>• Differential Privacy (DP) Noise Addition<br/>• 8-bit Model Quantization"]
        UAV3 --> LocalClient2
    end

    subgraph CentralHQ["DRDO Defense Command Cloud / Air Headquarters"]
        FedAgg["FedNeMo Central Orchestrator<br/>(FedAvg / FedProx Aggregator)<br/>• Aggregates encrypted gradients<br/>• Updates master fleet diagnostic weights<br/>• Verifies convergence without seeing raw sortie data"]
    end

    LocalClient1 -->|Encrypted Gradient Vectors Only<br/>(No GPS, No Flight Paths, No Raw Telemetry)| FedAgg
    LocalClient2 -->|Encrypted Gradient Vectors Only<br/>(No GPS, No Flight Paths, No Raw Telemetry)| FedAgg
    FedAgg -->|Downlink Updated Global Model Weights| LocalClient1
    FedAgg -->|Downlink Updated Global Model Weights| LocalClient2
```
"""

# -------------------------------------------------------------------------------------------------
# 2. DATA FLOWS AND EXECUTION FLOWS
# -------------------------------------------------------------------------------------------------
DOC_2_CONTENT = """# ANUMAAN — End-to-End Data Flows & Execution Lifecycles
**DRDO / SIH Problem Statement ID: 26054**

---

## 1. The 20 Hz Telemetry & Anomaly Detection Pipeline

This sequence captures the core operational loop that executes 20 times per second across all active engines:

```mermaid
sequenceDiagram
    autonumber
    participant Plant as VirtualEngine (PlantSource)
    participant Hub as RuntimeHub
    participant Det as ResidualDetector (Tier 0)
    participant Gate as PersistenceGate (3/5)
    participant Res as Reservoir / Classifier (Tier 1)
    participant Svr as FastAPI WebSocket Hub
    participant UI as React Ground Control Station

    loop 20 Ticks Per Second (50 ms interval)
        Plant->>Plant: Advance thermodynamics 1 simulated second
        Plant->>Hub: Yield Frame (t, rpm, map, cht[4], egt[4], oil_p, bus_v)
        Hub->>Det: Ingest Frame
        Det->>Det: Compute residuals: z = TailCalibration.z(frame)
        Det->>Det: Evaluate scorers: {fly_bloom, mahalanobis, max_abs_z}
        Det->>Det: Compare against Split-Conformal Thresholds
        Det->>Gate: Pass raw_alarm boolean
        Gate->>Gate: Update sliding window (k=3, n=5)
        alt Confirmed Alarm (>= 3 of last 5 frames tripped)
            Gate-->>Det: Confirmed Alarm = True
            Det->>Res: Trigger heavy candidate classification
            Res->>Res: Readout reservoir state -> candidate fault mode
            Det->>Hub: Return DetectionResult (scores, ratios, top_channels, candidate)
        else Normal Operation
            Gate-->>Det: Confirmed Alarm = False
            Det->>Hub: Return DetectionResult (scores, ratios, top_channels, NOMINAL)
        end
        Hub->>Svr: Broadcast EngineStatePayload to /ws/engines/{id} and /ws/fleet
        Svr->>UI: JSON Telemetry & Alarm Stream
        UI->>UI: Update Primary Flight Display, Gauge Needle, and Alert Banner
    end
```

---

## 2. High-Speed Crank-Angle Waveform & DSP Processing Flow

For failure modes invisible to scalar telemetry (such as injector coking, needle valve bounce, and piston slap), the high-rate waveform pipeline operates on individual engine four-stroke cycles:

```mermaid
flowchart TD
    subgraph WaveformAcq["1. Waveform Acquisition & Indexing"]
        ToothSens["Crankshaft 60-2 Reluctor Wheel<br/>Tooth Trigger Pulses (≤ 25 ns timing)"]
        CamSens["Camshaft Phase Sensor<br/>(Cylinder #1 TDC Compression Index)"]
        PressureSens["In-Cylinder Acoustic / Pressure Transducers<br/>(fs = 50 kHz - 100 kHz)"]
        
        ToothSens --> CycleBlock["CycleBlock Assembler (backend/core/cycle_block.py)<br/>Bins continuous time-series into 720° Crank-Angle Window"]
        CamSens --> CycleBlock
        PressureSens --> CycleBlock
    end

    subgraph DSPProcessing["2. Digital Signal Processing & Feature Extraction"]
        CycleBlock --> CA_Domain["Crank-Angle Domain Transformation<br/>p(θ), where θ ∈ [0°, 720°]"]
        CA_Domain --> IMEP_Calc["Indicated Mean Effective Pressure (IMEP):<br/>IMEP = (1 / Vd) ∮ p(θ) dV"]
        CA_Domain --> HRR_Calc["Rate of Heat Release (ROHR):<br/>dQ/dθ = (γ / γ-1) p dV/dθ + (1 / γ-1) V dp/dθ"]
        CA_Domain --> Knock_Filter["Bandpass Filtering (4 kHz - 8 kHz):<br/>Maximum Resonant Amplitude Metric"]
    end

    subgraph HealthVector["3. Cycle Health Synthesis"]
        IMEP_Calc --> CHV["CycleHealthVector (backend/core/cycle_block.py)<br/>• imep_per_cylinder [bar]<br/>• work_peer_ratio [-]<br/>• ca10, ca50, ca90 [° ATDC]<br/>• peak_pressure_angle [° ATDC]<br/>• knock_intensity_index [-]"]
        HRR_Calc --> CHV
        Knock_Filter --> CHV
    end

    subgraph Prognostics["4. Advanced Combustion Diagnostics"]
        CHV --> CombustCheck{"Combustion Peer Ratio Check"}
        CombustCheck -->|Cyl #1 Work < 85% Peer Average| ClogAlert["Flag INJECTOR_COKING (ATA 73-10)"]
        CombustCheck -->|ca50 Retarded > 8° BTDC| MisfireAlert["Flag IGNITION_TIMING_DRIFT (ATA 74-00)"]
        CombustCheck -->|Knock Index > Threshold| DetonationAlert["Flag CRITICAL_KNOCK / OCTANE_DEGRADE"]
    end
```

---

## 3. Deterministic ATA-Chapter Fault Diagnosis & Emergency Advisory Flow

When an anomaly is confirmed, ANUMAAN executes an immediate, deterministic diagnostic resolution mapped to aerospace standard ATA chapters:

```mermaid
flowchart TD
    AnomalyTrigger["Residual Detector Confirms Anomaly<br/>(e.g., CHT_2 > 135°C & EGT_2 Delta > 45°C)"]
    
    subgraph FMECA_Engine["FMECA Isolability Matrix (backend/reliability/fmeca.py)"]
        MatchSignatures["Signature Correlator:<br/>Compare normalized residual vector against<br/>pre-computed fault isolability matrix"]
        IsolateFault["Fault Isolated: Mode #1 (Cylinder #2 CHT Overheat)"]
        MatchSignatures --> IsolateFault
    end

    subgraph DeterministicAgent["Deterministic ATA Reasoner (backend/agent/diagnostic_agent.py)"]
        Lookup["Retrieve Rotax Maintenance Manual Spec:<br/>ATA Chapter: ATA 72-00 (Engine Core & Cooling)<br/>Manual Citation: Rotax 912 iS MM Chapter 72-00-00, Sec 4.2"]
        GenerateChecklist["Synthesize Pilot Emergency Checklist:<br/>Step 1: Throttle back to 4,600 RPM (loiter power)<br/>Step 2: Command +12% fuel enrichment to lower CHT<br/>Step 3: Descend 3,000–5,000 ft into denser, cooler air<br/>Step 4: Vector toward nearest recovery waypoint"]
        GenerateWorkOrder["Generate Ground Maintenance Order:<br/>Inspect Cylinder #2 cooling shroud and baffle elastomeric seals"]
        Lookup --> GenerateChecklist
        Lookup --> GenerateWorkOrder
    end

    subgraph Distribution["Downstream Distribution"]
        FlightDisplay["React GCS Cockpit HUD:<br/>• Red Alert Banner on CHT Gauge<br/>• Instant 4-Step Pilot Checklist Modal"]
        ThreeJS_Viewport["Three.js / Blender 3D Twin:<br/>• Eases camera to Cylinder #2 Head<br/>• Illuminates mesh Covers_Theme_M_PlasticTheme_0"]
        MissionManager["Mission Reliability Engine:<br/>• Recalculates Rm from 0.98 -> 0.72<br/>• Triggers RTB (Return-to-Base) advisory"]
    end

    AnomalyTrigger --> MatchSignatures
    IsolateFault --> Lookup
    GenerateChecklist --> FlightDisplay
    GenerateChecklist --> ThreeJS_Viewport
    GenerateChecklist --> MissionManager
```

---

## 4. Conformal Prediction RUL & Cumulative Damage Fatigue Flow

To solve the DRDO requirement for honest, statistically bounded Remaining Useful Life (RUL) estimation:

```mermaid
flowchart LR
    subgraph OperationalHistory["Sortie Operational History"]
        Hist["Cumulative Engine Operational Profiles<br/>(RPM, Load, Thermal Cycles, Altitude)"]
    end

    subgraph PhysicsFatigue["Cumulative Damage Models (backend/evaluation/damage_model.py)"]
        Arrhenius["Arrhenius Thermal Degradation:<br/>k(T) = A • exp(-Ea / (R • T))<br/>Computes thermal oil & valve guide decay"]
        MinersRule["Palmgren-Miner Linear Damage Accumulation:<br/>D = ∑ (ni / Ni)<br/>Calculates piston crown & cylinder head fatigue"]
        Hist --> Arrhenius
        Hist --> MinersRule
    end

    subgraph ConformalCalibration["Split-Conformal Calibration Engine (backend/evaluation/conformal.py)"]
        Holdout["Held-Out Run-to-Failure Calibration Data"]
        NonConf["Compute Non-Conformity Scores:<br/>si = |RUL_true,i - RUL_predicted,i|"]
        Quantile["Conformal Quantile Calibration:<br/>q_val = Quantile(1 - alpha)"]
        Holdout --> NonConf --> Quantile
    end

    subgraph IntervalOutput["Statistical Output"]
        PointEst["Raw RUL Point Estimate: 340 Hours"]
        ApplyBound["Apply Statistically Bounded Margin:<br/>[RUL_low, RUL_high] = [340 - q_val, 340 + q_val]<br/>Coverage Guarantee: 95% Confidence"]
        PointEst --> ApplyBound
        Quantile --> ApplyBound
    end

    subgraph MissionDecision["Mission Reliability (backend/mission/)"]
        ApplyBound --> Rm_Calc["Mission Completion Reliability (Rm):<br/>Rm = exp(- (t_mission / RUL_low)^beta)<br/>If Rm < 0.90 -> Recommend Abort / Divert"]
    end

    Arrhenius --> PointEst
    MinersRule --> PointEst
```

---

## 5. Local RAG Copilot & Voice Stream Flow

For hands-free ground control station operation during emergency scenarios:

```mermaid
sequenceDiagram
    autonumber
    actor Pilot as UAV Ground Pilot / Maintenance Engineer
    participant Mic as Audio Input Stream
    participant STT as Local Whisper STT (backend/voice/stt_engine.py)
    participant Store as LocalKnowledgeStore (backend/knowledge/)
    participant LLM as Local LLM Engine (Sarvam-30B / BharatGen via Ollama)
    participant TTS as Local Kokoro-82M TTS (backend/voice/tts_engine.py)
    participant Headset as Operator Headset

    Pilot->>Mic: "Engine 1 CHT is high, what is the immediate recovery procedure?"
    Mic->>STT: Raw PCM Audio Waveform
    STT->>STT: In-process Whisper Transcription
    STT->>Store: Text Query: "CHT high recovery procedure"
    Store->>Store: Vector Similarity Search + FlashRank Reranker over Rotax MM PDFs
    Store-->>LLM: Top-3 Retrieved Context Passages (ATA 72-00 Cooling SOP)
    LLM->>LLM: Deterministic Context Injection + Local Model Inference
    LLM-->>TTS: Text Response: "Rotax ATA 72 directive: Throttle to 4600 RPM, enrich fuel trim by 12 percent, descend 3000 feet."
    TTS->>TTS: Kokoro-82M High-Speed Neural Speech Synthesis
    TTS->>Headset: Clear synthesized audio alert directly into operator headset
```
"""

# -------------------------------------------------------------------------------------------------
# 3. IMPLEMENTED FEATURES, THEORY AND PROBLEM STATEMENT MAPPING
# -------------------------------------------------------------------------------------------------
DOC_3_CONTENT = """# ANUMAAN — Implemented Features, Theory & DRDO Alignment
**DRDO / SIH Problem Statement ID: 26054**

---

## Executive Feature Traceability Matrix

The table below correlates every implemented software feature in the repository with its theoretical foundations, implementation files, and the official DRDO Problem Statement requirement it fulfills:

| Feature Name | Theoretical / Engineering Foundation | Primary Implementation Files | DRDO PS-26054 Clause |
|---|---|---|---|
| **1D Thermodynamic Otto Cycle Twin** | First-principles 4-stroke thermodynamics, ICAO standard atmosphere derating, heat rejection balances | [`backend/physics/thermo_model.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/physics/thermo_model.py), [`engine_model.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/physics/engine_model.py) | §2 (Thermodynamic behavior models) |
| **Independent Virtual Plant (`VirtualEngine`)** | Physical model mismatch, stochastic build variation, sensor transfer functions, non-linear turbo dynamics | [`backend/plant/virtual_engine.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/plant/virtual_engine.py), [`adapter.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/plant/adapter.py) | §3.A (Synchronized virtual representation) |
| **Split-Conformal Residual Detector** | Split-conformal prediction quantiles, Locality Sensitive Hashing (FlyBloom), Mahalanobis metric | [`backend/detect/detector.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/detect/detector.py), [`scorers.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/detect/scorers.py), [`calibration.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/detect/calibration.py) | §2 & §3.C (Predictive anomaly detection) |
| **Multi-Engine Configuration Catalog** | Dimensionless scaling, bore/stroke geometry tables, SI vs. CI fuel injection, turbo maps | [`configs/engines/`](file:///e:/backup-llm/backup-no-llm/3d_engine/configs/engines), [`backend/physics/engine_config.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/physics/engine_config.py) | §2 (Scalable and modular digital twin) |
| **DRDO 8-Class Neural Fault Classifier** | Multi-class supervised pattern recognition, FMECA cross-correlation matrices | [`backend/ml/detection_pipeline.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/ml/detection_pipeline.py), [`fault_classifier.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/ml/fault_classifier.py) | §3.C (Fault Detection & Predictive Analytics) |
| **Deterministic ATA-Chapter Diagnostic Agent** | Aerospace ATA 71–80 chapters, deterministic expert rule graphs, prescriptive checklists | [`backend/agent/diagnostic_agent.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/agent/diagnostic_agent.py) | §3.C (SOP-grounded prescriptive action) |
| **Statistically Bound Conformal RUL** | Conformal calibration coverage bounds, non-conformity quantiles | [`backend/evaluation/conformal.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/evaluation/conformal.py), [`backend/ml/rul_estimator.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/ml/rul_estimator.py) | §2 & §3.D (Remaining Useful Life estimation) |
| **Cumulative Damage Accumulation Model** | Arrhenius reaction kinetics (thermal degradation) + Palmgren-Miner linear fatigue damage | [`backend/evaluation/damage_model.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/evaluation/damage_model.py) | §2 (Degradation trends and life-cycle) |
| **High-Rate 20 Hz WebSocket Server** | Asynchronous IO, pub/sub WebSocket channels, atomic state caching | [`backend/server/main.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/server/main.py), [`engine_api.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/server/engine_api.py) | §3.A (Real-time data ingestion capability) |
| **React Ground Control Station (GCS)** | Cyber-physical telemetry HUD, glass-cockpit instruments, dynamic fault injection levers | [`frontend/src/`](file:///e:/backup-llm/backup-no-llm/3d_engine/frontend/src) | §2 (Dashboard/HMI for operators) |
| **Blender 3D Viewport Digital Twin** | Procedural thermal shaders, hierarchical CAD meshes, camera transition math | [`apps/blender_twin/`](file:///e:/backup-llm/backup-no-llm/3d_engine/apps/blender_twin) | §2 (Real-time engine parameter visualization) |
| **Canyon Flight Simulation (Ladakh)** | Digital Elevation Model (DEM) terrain rendering, waypoint navigation simulation | [`assets/models/terrain.blend`](file:///e:/backup-llm/backup-no-llm/3d_engine/assets/models/terrain.blend), [`launch_canyon_simulation.bat`](file:///e:/backup-llm/backup-no-llm/3d_engine/launch_canyon_simulation.bat) | §2 (Simulating behavior under mission profiles) |
| **Offline RAG Knowledge Copilot** | Vector embeddings, sentence-transformers, FlashRank reranking, local Ollama LLMs | [`backend/knowledge/`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/knowledge), [`backend/agent/copilot.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/agent/copilot.py) | §3.D (Intelligent maintenance planning) |
| **Local STT / TTS Voice Assistant** | Offline OpenAI Whisper STT, Kokoro-82M neural TTS, zero-cloud audio pipeline | [`backend/voice/stt_engine.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/voice/stt_engine.py), [`tts_engine.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/voice/tts_engine.py) | §2 (Pilot/operator hands-free interface) |
| **Mission Knowledge Graph Database** | Graph theory, NetworkX, temporal sortie persistence, anomaly-to-maintenance linking | [`backend/graph/`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/graph), [`apps/mission_graph_viewer/`](file:///e:/backup-llm/backup-no-llm/3d_engine/apps/mission_graph_viewer) | §2 & §3.A (Post-flight analysis & operational history) |
| **High-Rate Crank Waveform DSP** | High-resolution timestamping (≤ 25 ns), indicated work integration, knock filtering | [`backend/core/cycle_block.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/core/cycle_block.py), [`backend/plant/sensors_hr.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/plant/sensors_hr.py) | §3.B (Combustion instability & injection timing) |
| **Privacy-Preserving Federated Learning** | Federated Averaging (FedAvg / FedProx), Differential Privacy (DP), gradient quantization | [`FedNeMo/v1/fednemo/`](file:///e:/backup-llm/backup-no-llm/3d_engine/FedNeMo/v1/fednemo) | §3 (Fleet-level health monitoring infrastructure) |
| **Autonomous Mission Flight Planning** | Dynamic obstacle avoidance, terrain-following, energy-optimal climb/descent profiles | [`mission-planning/`](file:///e:/backup-llm/backup-no-llm/3d_engine/mission-planning) | §1 & §2 (Mission reliability enhancement & planning) |

---

## Detailed Feature Engineering Deep-Dives

### 1. 1D Thermodynamic Otto Cycle Physics Model
- **Theory & Mathematics:**
  The engine power and heat generation are governed by the four-stroke Otto thermodynamic cycle with altitude derating:
  $$P_{\\text{indicated}} = \\frac{V_d \\times \\text{RPM} \\times \\text{MAP} \\times \\eta_v}{120} \\times \\left[ 1 - \\frac{1}{r^{\\gamma - 1}} \\right]$$
  Where $V_d = 1.352\\text{ L}$, $r = 10.8$, and $\\gamma = 1.35$.
  Ambient air density at altitude $h$ is modeled using the standard ISA barometric equations:
  $$T_{\\text{amb}} = 288.15 - 0.0019812 \\times h_{\\text{ft}}, \\quad P_{\\text{amb}} = 101.325 \\times \\left( \\frac{T_{\\text{amb}}}{288.15} \\right)^{5.25588}$$
  $$\\sigma = \\frac{\\rho_{\\text{amb}}}{\\rho_{\\text{sea-level}}}$$
  The expected CHT baseline is derived by balancing heat generation against forced air convection:
  $$\\text{CHT}_{\\text{expected}} = T_{\\text{OAT}} + 85.0 \\times \\left( \\frac{\\text{TPS}}{100} \\right)^{0.75} \\times \\left( \\frac{\\text{RPM}}{5000} \\right)^{0.5}$$
- **Why It Was Implemented:** To establish a physics-grounded reference state that enables anomaly detection based on physical residuals ($y - \\hat{y}$) rather than raw arbitrary sensor thresholds.

---

### 2. Independent Virtual Plant (`VirtualEngine`)
- **Theory & Engineering:**
  In a real manufacturing environment, no two engines are identical. `VirtualEngine` implements stochastic build variation:
  $$\\text{Variation} = \\{ \\eta_{v,\\text{scale}} \\sim \\mathcal{N}(1.0, 0.02), \\quad f_{\\text{friction}} \\sim \\mathcal{N}(1.0, 0.06), \\quad h_{\\text{transfer}} \\sim \\mathcal{N}(1.0, 0.045) \\}$$
  Sensors do not measure reality instantly; they exhibit first-order low-pass thermal lag and bias:
  $$\\frac{dT_{\\text{sensor}}}{dt} = \\frac{1}{\\tau} (T_{\\text{actual}} - T_{\\text{sensor}}) + \\beta_{\\text{drift}}$$
- **Why It Was Implemented:** Closes architectural flaw G01. Guarantees that diagnostic algorithms are tested against genuine model mismatch and sensor imperfections rather than checking their own generator.

---

### 3. Split-Conformal Residual Anomaly Detector (Tier 0)
- **Theory & Mathematics:**
  Given a sequence of nominal calibration frames $F_1, \\dots, F_n$, the detector extracts 13 residual features $z_i = (x_i - \\mu_i) / \\sigma_i$ and evaluates three non-conformity scorers:
  1. **Max Absolute Z-Score:** $s_1 = \\max_j |z_j|$
  2. **Mahalanobis Distance:** $s_2 = \\sqrt{z^T \\Sigma^{-1} z}$
  3. **FlyBloom LSH Scorer:** Random sparse projection into 256 Kenyon cell activations, checking novel bit density.
  For a designated false-alarm significance level $\\alpha$ (e.g. $\\alpha = 0.01$), the conformal threshold $\\tau$ is computed as the finite-sample quantile:
  $$\\tau = \\text{Quantile}\\left( \\frac{\\lceil (n + 1)(1 - \\alpha) \\rceil}{n}, \\; \\{ s(F_i) \\}_{i=1}^n \\right)$$
  To eliminate spurious false alarms from flight turbulence, a `PersistenceGate` confirms the alarm only if $\\ge 3$ of the last 5 ticks exceed $\\tau$.
- **Why It Was Implemented:** Solves the notorious false-alarm problem in defense condition monitoring, providing a mathematically guaranteed upper bound on false-alarm rates during combat sorties.

---

### 4. Deterministic ATA-Chapter Diagnostic Directives
- **Theory & Engineering:**
  Aerospace operations require certification under FAA/EASA and DRDO SOPs. An emergency flight directive cannot depend on a generative model that might hallucinate non-existent valves or incorrect airspeeds.
  The engine maps the 8 DRDO fault modes to deterministic directives:
  - **Mode 1 (Cylinder #2 Overheat):** ATA 72-00 $\\to$ Throttle back to 4,600 RPM, enrich fuel trim +12%, descend 3,000 ft.
  - **Mode 2 (Injector #1 Clog):** ATA 73-10 $\\to$ Verify rail pressure, force FADEC to Lane B backup schedule, engage auxiliary boost pump.
  - **Mode 3 (Ignition Misfire):** ATA 74-00 $\\to$ Toggle ignition lanes (Lane A $\\to$ Lane B), stabilize at loiter RPM.
  - **Mode 4 (Oil Pressure Loss):** ATA 79-00 $\\to$ Immediate critical warning; throttle to minimum safe glide power, initiate emergency landing sequence.
- **Why It Was Implemented:** Provides instantaneous, 100% reproducible, airworthiness-compliant pilot instructions during mission-critical propulsion emergencies.

---

### 5. Conformal-Calibrated Remaining Useful Life (RUL) & Mission Reliability ($R_m$)
- **Theory & Mathematics:**
  Predicting a single number for RUL (e.g. "300 hours") is dangerous in aviation because point estimates provide no uncertainty bound.
  ANUMAAN combines cumulative Arrhenius thermal aging with Palmgren-Miner fatigue:
  $$D_{\\text{total}} = \\sum_{i} \\frac{n_i}{N_i} + \\int A \\cdot \\exp\\left( -\\frac{E_a}{R \\cdot T(t)} \\right) dt$$
  Applying split-conformal calibration on run-to-failure historical engines yields a bounded confidence interval:
  $$[\\text{RUL}_{\\text{lower}}, \\; \\text{RUL}_{\\text{upper}}] = [\\widehat{\\text{RUL}} - q_{1-\\alpha}, \\; \\widehat{\\text{RUL}} + q_{1-\\alpha}]$$
  The Mission Reliability $R_m$ for an upcoming planned sortie duration $t_{\\text{mission}}$ is then computed using the conservative lower bound:
  $$R_m = \\exp\\left( - \\left( \\frac{t_{\\text{mission}}}{\\text{RUL}_{\\text{lower}}} \\right)^\\beta \\right)$$
  If $R_m < 0.90$, the system automatically issues a prescriptive mission abort / flight plan divert directive.
- **Why It Was Implemented:** Directly fulfills DRDO Problem Statement §1 & §2: enhancing mission reliability and preventing in-flight asset loss.
"""

# -------------------------------------------------------------------------------------------------
# 4. CORRELATION MATRIX AND MINDMAPS
# -------------------------------------------------------------------------------------------------
DOC_4_CONTENT = """# ANUMAAN — Component Correlation Matrix & Universal Mind Maps
**DRDO / SIH Problem Statement ID: 26054**

---

## Universal Project Mind Map

The visual diagram below maps every major directory and functional package in the repository into its respective systems engineering domain:

```mermaid
mindmap
  root((ANUMAAN Digital Twin<br/>DRDO PS-26054))
    Propulsion Models
      backend/physics
        thermo_model.py (Otto 1D thermodynamic equations)
        crank_dynamics.py (Reciprocating mass kinetics)
        turbo_model.py (Compressor/turbine maps)
        engine_config.py (Multi-engine geometries)
      backend/plant
        virtual_engine.py (Independent ground-truth plant)
        adapter.py (PlantSource bridge)
        sensors_hr.py (High-rate waveform generators)
      configs/engines
        rotax_912_is.json (Nominal baseline)
        rotax_914.json (Turbocharged)
        rotax_915_is.json (High-altitude turbo)
        austro_ae300.json (Common-rail diesel)
        vrde_jayem_2_2l.json (Defense indigenous diesel)
    Diagnostics & Prognostics
      backend/detect
        detector.py (Split-conformal residual detector)
        scorers.py (FlyBloom LSH, Mahalanobis, MaxAbsZ)
        calibration.py (Tail baseline calibration)
        reservoir.py (Randomized tier-1 classifier)
      backend/ml
        detection_pipeline.py (DRDO 8 fault modes)
        rul_estimator.py (Remaining Useful Life)
        combustion_diagnostics.py (IMEP / Knock)
      backend/evaluation
        conformal.py (Finite-sample coverage guarantees)
        damage_model.py (Miner fatigue + Arrhenius thermal)
      backend/agent
        diagnostic_agent.py (Deterministic ATA-chapter reasoner)
        copilot.py (Local conversational assistant)
    Real-Time Services
      backend/server
        main.py (FastAPI gateway & lifespan)
        engine_api.py (Multi-engine REST & WebSocket hub)
        engine_service.py (Legacy state service)
      backend/telemetry
        can_streamer.py (20 Hz socket publisher)
        replay_engine.py (Historical flight replayer)
        aces_loader.py (NASA ACES MAT parser)
    Human-Machine Interfaces
      frontend (React + Vite + Tailwind)
        EngineRuntimeConsole.tsx (Multi-engine dashboard)
        HUDOverlay.tsx (Primary flight instruments)
        DiagnosticCard.tsx (ATA prescriptive alerts)
      apps/blender_twin
        standalone_digital_twin_app.py (EEVEE 3D viewport)
        canyon_flight_sim.py (Ladakh simulation)
      apps/desktop_gcs
        main.py (Pygame hardware-accelerated HUD)
      web/site
        index.html (Three.js WebGL engine showcase)
    Advanced Ecosystems
      FedNeMo
        v1/fednemo/federated (Differential privacy fleet PHM)
      mission-planning
        backend/mission (Dynamic obstacle / waypoint navigation)
      mk-jev-fly-brain
        Connectome-inspired reservoir benchmark
```

---

## Detailed Cross-Module Traceability Matrix

The following matrix provides comprehensive architectural correlation, mapping each subsystem's inputs, outputs, execution rate, and internal dependencies:

| Subsystem / Module | Source File(s) | Upstream Producer (Inputs) | Downstream Consumer (Outputs) | Cadence / Trigger | Data Contract | Primary Role in System |
|---|---|---|---|---|---|---|
| **Virtual Plant** | [`backend/plant/virtual_engine.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/plant/virtual_engine.py) | Operator control levers (throttle, altitude, OAT) + Injected fault modes | `RuntimeHub` & `PlantSource` | 20 Hz (simulated 1s/tick) | `Frame` + `TruthRecord` | Generates ground-truth physics with independent manufacturing variation and sensor noise. |
| **Thermodynamic Observer** | [`backend/physics/thermo_model.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/physics/thermo_model.py) | Raw `Frame` telemetry channels | `ResidualDetector` & legacy streamer | Per-tick / On-demand | `EnginePhysicalState` | Calculates first-principles theoretical CHT, EGT, MAP, and fuel mass flow baselines. |
| **Residual Detector** | [`backend/detect/detector.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/detect/detector.py) | Incoming `Frame` from plant or hardware | `RuntimeHub`, WebSocket, Tier 1 Classifier | 20 Hz synchronous | `DetectionResult` | Performs split-conformal anomaly detection with explainable leading residual channels. |
| **Persistence Gate** | [`backend/detect/detector.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/detect/detector.py) | Raw boolean alarm from scorers | `ResidualDetector.confirmed` | Per-tick evaluation | Boolean confirmation | Filters out transient spikes using a sliding window ($k=3$ of $n=5$ frames). |
| **Runtime Hub** | [`backend/runtime/hub.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/runtime/hub.py) | Engine configs in `configs/engines/` | `backend/server/engine_api.py` | 20 Hz wall clock | JSON state dictionaries | Manages concurrent multi-engine instances, calibrating baselines and advancing ticks. |
| **FastAPI Engine API** | [`backend/server/engine_api.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/server/engine_api.py) | `RuntimeHub` ticks | React GCS, Three.js WebGL twin | Continuous REST / WebSocket | `/ws/engines/{id}`, `/ws/fleet` | Exposes REST levers and real-time WebSocket state streaming to user interfaces. |
| **ATA Diagnostic Agent** | [`backend/agent/diagnostic_agent.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/agent/diagnostic_agent.py) | Confirmed anomaly from detector or legacy pipeline | GCS alert banner, Three.js locator, pilot debrief | Event-driven upon anomaly | `DiagnosticDirective` | Emits deterministic, airworthiness-grounded emergency checklists and maintenance work orders. |
| **Conformal Evaluator** | [`backend/evaluation/conformal.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/evaluation/conformal.py) | Calibration run-to-failure datasets | `rul_estimator.py` & Mission Reliability | Offline calibration / On-demand | Statistical bounds $[\\text{RUL}_l, \\text{RUL}_u]$ | Computes non-conformity quantiles providing 95% statistical coverage guarantees. |
| **Damage Accumulator** | [`backend/evaluation/damage_model.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/evaluation/damage_model.py) | Telemetry history (thermal cycles, RPM fatigue) | Conformal RUL estimator | Periodic / Post-sortie | Cumulative Damage Fraction $D$ | Computes Arrhenius thermal aging of oil/valves and Palmgren-Miner cyclic fatigue. |
| **Blender 3D Twin** | [`apps/blender_twin/standalone_digital_twin_app.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/apps/blender_twin/standalone_digital_twin_app.py) | WebSocket `/ws/telemetry` or TCP socket | Human operator viewport display | 30–60 FPS graphics render | Blender scene graph | Renders real-time EEVEE 3D engine CAD with thermal shaders, exploded views, and camera easing. |
| **React GCS HUD** | [`frontend/src/components/HUDOverlay.tsx`](file:///e:/backup-llm/backup-no-llm/3d_engine/frontend/src/components) | WebSocket `/ws/engines/{id}` | Ground pilot / flight engineer | 20 Hz DOM update | React UI State | Visualizes flight instruments (RPM, CHT, EGT, Oil P, Volts) with color-coded threshold zones. |
| **Local Knowledge Store** | [`backend/knowledge/retrieval/store.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/knowledge/retrieval/store.py) | Manuals in `data/documents/` (Rotax MM, SOPs) | `backend/agent/copilot.py` | Query-triggered | Text chunk context vectors | Performs offline vector search and FlashRank reranking over technical manuals. |
| **Voice STT / TTS** | [`backend/voice/`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/voice) | Pilot microphone audio input | Operator headset audio feed | Voice-activity triggered | PCM audio buffers | Provides air-gapped speech recognition (Whisper) and neural audio synthesis (Kokoro-82M). |
| **Mission Graph DB** | [`backend/graph/graph_store.py`](file:///e:/backup-llm/backup-no-llm/3d_engine/backend/graph) | Sortie execution logs and maintenance sign-offs | `apps/mission_graph_viewer/` | End of sortie / Maintenance event | NetworkX JSON graph | Persists fleet operational history, linking airframe tails to sorties, anomalies, and part replacements. |
| **Federated Engine** | [`FedNeMo/v1/fednemo/federated/`](file:///e:/backup-llm/backup-no-llm/3d_engine/FedNeMo/v1/fednemo/federated) | Airframe sortie datasets across dispersed bases | Central fleet model aggregator | Post-sortie federated round | Quantized, noisy gradient tensors | Aggregates diagnostic weights across multiple airbases using differential privacy. |
"""

# -------------------------------------------------------------------------------------------------
# 5. MASTER INTEGRATED ARCHITECTURAL KNOWLEDGE HANDBOOK
# -------------------------------------------------------------------------------------------------
DOC_5_CONTENT = f"""# ANUMAAN — Master Integrated Architectural Knowledge Handbook
**DRDO / SIH Problem Statement ID: 26054**
*AI-Enabled Real-Time Digital Twin System for Health Monitoring, Fault Prediction and Mission Reliability Enhancement of Aero Piston Engines used in MALE UAVs*

---

## Complete Executive Overview

Project ANUMAAN (अनुमान — Sanskrit for *"inference/prediction"*) is an indigenous cyber-physical digital twin architecture engineered for Medium Altitude Long Endurance (MALE) Unmanned Aerial Vehicles (e.g., TAPAS-BH-201 / Rustom-II). The platform addresses the vulnerability of conventional threshold-based monitoring systems by combining:
1. **First-Principles Thermodynamics (1D Otto Cycle Physics)**
2. **Physically Independent Plant Modeling (`VirtualEngine`)**
3. **Split-Conformal Statistical Anomaly Detection (Tier 0)**
4. **Deterministic ATA-Chapter Prescriptive Diagnostics (Zero Hallucination)**
5. **Calibrated Remaining Useful Life (RUL) & Mission Reliability ($R_m$)**
6. **Real-Time 20 Hz WebSocket Ground Control Station & 3D CAD Visualization**
7. **Privacy-Preserving Fleet Federated Learning (`FedNeMo`)**

---

{DOC_1_CONTENT}

---

{DOC_2_CONTENT}

---

{DOC_3_CONTENT}

---

{DOC_4_CONTENT}
"""

def main():
    print("Writing architecture documents to final_touch/ and final touch/...")
    
    docs = [
        ("SYSTEM_ARCHITECTURE_AND_MENTAL_MODELS.md", DOC_1_CONTENT),
        ("DATA_FLOWS_AND_EXECUTION_FLOWS.md", DOC_2_CONTENT),
        ("IMPLEMENTED_FEATURES_THEORY_AND_MAPPING.md", DOC_3_CONTENT),
        ("CORRELATION_MATRIX_AND_MINDMAPS.md", DOC_4_CONTENT),
        ("MASTER_INTEGRATED_ARCHITECTURAL_KNOWLEDGE.md", DOC_5_CONTENT),
    ]
    
    for filename, content in docs:
        p1 = FINAL_TOUCH / filename
        p2 = FINAL_TOUCH_SPACE / filename
        
        with open(p1, "w", encoding="utf-8") as f:
            f.write(content)
        with open(p2, "w", encoding="utf-8") as f:
            f.write(content)
            
        print(f"Generated {filename}: {os.path.getsize(p1):,} bytes")

    print("All architectural knowledge documents successfully generated!")

if __name__ == "__main__":
    main()
