"""
Cognitive Diagnostic Agent & ATA Citation Reasoner — Plane 2
DRDO / iDEX Problem Statement ID: 26054

Provides authoritative, ATA-cited prescriptive directives grounded in official
Rotax 912 iS Maintenance Manuals (ATA 72-79) and DRDO Standard Operating Procedures (SOP).

PS reference: doc01 §3 Pillar 3 — "Prescriptive Action Directives with ATA citations"
doc02 §5 Plane 2 — "Local LLM / SLM or Rule-Based Diagnostic Reasoner"
Operates 100% offline, air-gapped, zero cloud or external API dependencies.
"""

from dataclasses import dataclass, field, asdict
from typing import Dict, Any, List, Optional
import os
import re
import sys


@dataclass
class DiagnosticDirective:
    """Authoritative prescriptive directive generated by the Diagnostic Agent."""
    fault_id: int
    fault_name: str
    ata_chapter: str
    manual_reference: str
    subsystem: str
    target_3d_mesh: str
    severity: str
    root_cause_explanation: str
    causal_chain: List[str]
    prescriptive_action: str
    emergency_checklist: List[str]
    maintenance_order: str
    confidence: float
    relevance_score: float
    # 1-based index of the cylinder this directive is about, or None for engine-level
    # faults. The UI uses this to highlight one cylinder rather than the whole bank, so
    # it must reflect the cylinder actually implicated rather than the template's.
    cylinder: Optional[int] = None

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


# Authoritative DRDO / Rotax 912 iS ATA Expert Knowledge Dictionary
ROTAX_ATA_FAULT_DIRECTIVES: Dict[int, Dict[str, Any]] = {
    1: {
        "template_cylinder": 2,
        "fault_name": "Cylinder #2 CHT Overheat",
        "ata_chapter": "ATA 72-00",
        "manual_reference": "Rotax 912 iS MM Chapter 72-00-00, Section 4.2 (Cylinder Head Cooling)",
        "subsystem": "ENGINE_CORE_COOLING",
        "target_3d_mesh": "Covers_Theme_M_PlasticTheme_0",
        "severity": "CRITICAL",
        "root_cause_explanation": "Cooling baffle seal displacement on Cylinder #2 shroud leading to localized thermal boundary layer separation and progressive CHT runaway.",
        "causal_chain": [
            "Baffle seal displacement restricts cooling airflow over Cyl #2 fins.",
            "Cylinder #2 head temperature (CHT #2) climbs into critical boundary (>140°C).",
            "Crankcase oil heat absorption raises overall oil temperature (+10.5°C).",
            "Combustion wall heat accelerates flame front, causing EGT #2 to elevate."
        ],
        "prescriptive_action": "Enrich fuel trim +12%, reduce throttle to 4,600 RPM, and initiate descent to cooler ambient air.",
        "emergency_checklist": [
            "Step 1: Throttle back to 4,600 RPM (loiter power) to reduce heat rejection.",
            "Step 2: Command +12% fuel enrichment to lower combustion chamber temperatures.",
            "Step 3: Descend 3,000–5,000 ft into denser, cooler ambient air.",
            "Step 4: If CHT exceeds 135°C, vector toward nearest recovery waypoint."
        ],
        "maintenance_order": "Inspect Cylinder #2 cooling shroud and baffle elastomeric seals for tears, deformation, or dislodgement."
    },
    2: {
        "template_cylinder": 1,
        "fault_name": "Fuel Injector #1 Clog",
        "ata_chapter": "ATA 73-10",
        "manual_reference": "Rotax 912 iS MM Chapter 73-10-00, Section 3.1 (High-Pressure Fuel Injection)",
        "subsystem": "FUEL_INJECTION_SYSTEM",
        "target_3d_mesh": "Rotax_912i_Base_M_PlasticGreen_0",
        "severity": "CRITICAL",
        "root_cause_explanation": "Particulate restriction or nozzle cavitation at Injector #1 delivery port causing lean combustion and single-cylinder EGT divergence.",
        "causal_chain": [
            "Electromagnetic fuel injector #1 delivery nozzle partially restricted.",
            "Fuel flow rate drops by ~22%, starving Cylinder #1 into lean burn.",
            "Extreme lean air-fuel ratio causes EGT #1 spike (+92°C) and head temp rise.",
            "Single-cylinder power loss creates cyclic torque ripple and vibration rise."
        ],
        "prescriptive_action": "Switch FADEC control map to Lane B backup schedule and activate auxiliary electric fuel boost pump.",
        "emergency_checklist": [
            "Step 1: Verify fuel rail delivery pressure on primary instrument panel.",
            "Step 2: Force FADEC arbitration to Lane B auxiliary injection schedule.",
            "Step 3: Engage auxiliary electric fuel pump to stabilize rail pressure.",
            "Step 4: Monitor Cylinder #1 EGT for stabilization."
        ],
        "maintenance_order": "Remove Injector #1 and perform ultrasonic nozzle backflush and flow-rate calibration."
    },
    3: {
        "template_cylinder": 2,
        "fault_name": "Ignition Misfire (Lane A)",
        "ata_chapter": "ATA 74-20",
        "manual_reference": "Rotax 912 iS MM Chapter 74-20-00, Section 2.4 (Dual Ignition System)",
        "subsystem": "IGNITION_SYSTEM",
        "target_3d_mesh": "Wiring_Harness_M_Copper_0",
        "severity": "WARNING",
        "root_cause_explanation": "Primary ignition coil degradation or spark plug lead insulation breakdown on Lane A circuit causing intermittent combustion dropouts.",
        "causal_chain": [
            "Secondary spark plug lead insulation breakdown causes intermittent misfire.",
            "Unburnt fuel expelling into exhaust runner drops EGT #2 sharply (-125°C).",
            "Periodic combustion loss produces high-variance engine RPM flutter.",
            "Crankshaft torque shocks transmit into reduction gearbox vibration (+1.45 mm/s)."
        ],
        "prescriptive_action": "Switch FADEC ignition arbitration to redundant Lane B coil circuit.",
        "emergency_checklist": [
            "Step 1: Select Ignition Lane B via GCS engine control panel.",
            "Step 2: Monitor RPM stability and confirm vibration jitter reduction.",
            "Step 3: Maintain cruise power and continue mission on Lane B."
        ],
        "maintenance_order": "Perform ignition lead resistance test (nominal 4.5-5.5 kOhm) and replace Lane A coil pack."
    },
    4: {
        "fault_name": "Oil Pressure Loss",
        "ata_chapter": "ATA 79-00",
        "manual_reference": "Rotax 912 iS MM Chapter 79-00-00, Section 5.1 (Dry Sump Lubrication)",
        "subsystem": "LUBRICATION_SYSTEM",
        "target_3d_mesh": "Oil_Tank_M_Steel_0",
        "severity": "CRITICAL",
        "root_cause_explanation": "Pressure relief valve seat contamination or scavenge pump cavitation causing linear oil pressure decay.",
        "causal_chain": [
            "Scavenge line cavitation or relief bypass spring fatigue decays oil pressure.",
            "Oil pressure collapses down to 1.6-1.8 bar, thinning bearing oil wedge.",
            "Hydrodynamic friction generates rapid oil temperature surge (+28°C).",
            "Mechanical friction conducts heat to all cylinders and drags down engine RPM."
        ],
        "prescriptive_action": "Reduce engine RPM to 4,200 RPM to minimize bearing load and initiate immediate precautionary RTB vector.",
        "emergency_checklist": [
            "Step 1: Reduce power immediately to minimum safe flying airspeed (4,200 RPM).",
            "Step 2: Monitor oil temperature trend for secondary thermal runaway.",
            "Step 3: Declare emergency and vector directly to nearest runway/recovery zone.",
            "Step 4: Prepare for engine shutdown upon final approach."
        ],
        "maintenance_order": "Inspect oil suction screen, scavenge pump gears, and oil filter element for metallic particulate contamination."
    },
    5: {
        "fault_name": "Gearbox Vibration & Clutch Wear",
        "ata_chapter": "ATA 72-10",
        "manual_reference": "Rotax 912 iS MM Chapter 72-10-00, Section 6.3 (Propeller Reduction Gearbox)",
        "subsystem": "REDUCTION_GEARBOX",
        "target_3d_mesh": "Gearbox_Type_2_M_Steel_0",
        "severity": "WARNING",
        "root_cause_explanation": "Dog-clutch overload mechanism micro-pitting and gear backlash producing elevated 3rd harmonic spectral energy.",
        "causal_chain": [
            "Propeller reduction dog-clutch tooth pitting excites 3rd harmonic resonance.",
            "Gearbox vibration RMS surges to >3.5 mm/s, exceeding safety limits.",
            "Parasitic drivetrain drag sags engine RPM and triggers FADEC MAP compensation.",
            "Gear mesh frictional dissipation elevates front crankcase oil temperature."
        ],
        "prescriptive_action": "Limit rapid throttle transients, avoid critical RPM resonance zones (4,000-4,400 RPM), and schedule post-flight clutch overhaul.",
        "emergency_checklist": [
            "Step 1: Smooth throttle movements to prevent dog-clutch impact shock.",
            "Step 2: Operate outside resonance band (hold steady at 4,800-5,000 RPM).",
            "Step 3: Monitor reduction shaft vibration RMS."
        ],
        "maintenance_order": "Perform gearbox backlash measurement (max allowable 0.05 mm) and dog-clutch spring pack inspection."
    },
    6: {
        "template_cylinder": 3,
        "fault_name": "Exhaust EGT Imbalance",
        "ata_chapter": "ATA 78-10",
        "manual_reference": "Rotax 912 iS MM Chapter 78-10-00, Section 2.1 (Exhaust Manifold & Tuning)",
        "subsystem": "EXHAUST_SYSTEM",
        "target_3d_mesh": "Exhaust_System_M_SteelDark_0",
        "severity": "WARNING",
        "root_cause_explanation": "Runner #3 air-fuel mixture disparity or manifold gasket micro-leakage causing localized exhaust temperature divergence.",
        "causal_chain": [
            "Runner #3 intake gasket leak or mixture offset creates localized lean burn.",
            "Exhaust runner #3 temperature diverges sharply (+95°C above baseline).",
            "Cylinder #3 head absorbs excess combustion heat (+18°C CHT rise).",
            "Asymmetric exhaust scavenging produces mild RPM drag and vibration rise."
        ],
        "prescriptive_action": "Adjust individual cylinder fuel trim offset on Cylinder #3 by +6%.",
        "emergency_checklist": [
            "Step 1: Cross-check CHT distribution across all 4 cylinders.",
            "Step 2: Apply +6% trim offset to Cylinder #3 via GCS FADEC calibration panel.",
            "Step 3: Verify EGT delta drops below 65°C."
        ],
        "maintenance_order": "Inspect exhaust runner flange torque and check for micro-cracks at header collectors."
    },
    7: {
        "fault_name": "Alternator Voltage Sag",
        "ata_chapter": "ATA 24-00",
        "manual_reference": "Rotax 912 iS MM Chapter 24-00-00, Section 4.1 (Electrical Power Generation)",
        "subsystem": "ELECTRICAL_POWER_GENERATION",
        "target_3d_mesh": "External_Alternator_M_GreyDark_0",
        "severity": "WARNING",
        "root_cause_explanation": "Internal stator winding thermal stress or voltage regulator duty cycle saturation under high payload electrical load.",
        "causal_chain": [
            "Heavy-duty alternator stator winding thermal sag reduces generator output.",
            "DC bus voltage drops from 14.1V to ~12.2V, below battery floating potential.",
            "Battery swings to heavy discharge (-15.5A) to sustain avionics and ignition.",
            "Sub-optimal coil charging dwell induces mild engine RPM power sag."
        ],
        "prescriptive_action": "Shed non-essential ISR payload sensors and engage backup avionics battery bus.",
        "emergency_checklist": [
            "Step 1: Shed high-draw secondary reconnaissance payloads (SAR/Optics heating).",
            "Step 2: Verify primary bus voltage recovers above 13.5V.",
            "Step 3: Monitor battery state of charge (SOC)."
        ],
        "maintenance_order": "Test alternator stator phase-to-phase resistance and check regulator grounding harness."
    },
    8: {
        "fault_name": "Dual FADEC ECU Drift",
        "ata_chapter": "ATA 76-00",
        "manual_reference": "Rotax 912 iS MM Chapter 76-00-00, Section 3.2 (Engine Control & ECU Arbitration)",
        "subsystem": "ENGINE_CONTROL_UNIT",
        "target_3d_mesh": "ECU_M_PlasticDark_0",
        "severity": "WARNING",
        "root_cause_explanation": "Manifold absolute pressure (MAP) sensor calibration divergence exceeding cross-channel plausibility limits between Lane A and Lane B.",
        "causal_chain": [
            "Dual FADEC Lane A MAP transducer drifts positive by +9.5 kPa.",
            "Speed-density calculation commands excessive fuel mass across all cylinders.",
            "Fuel flow rises (+3.2 L/h) causing over-rich combustion across all 4 cylinders.",
            "Over-rich mixture cools all exhaust runners (-45°C EGT) and sags engine power."
        ],
        "prescriptive_action": "Force FADEC arbitration to Lane B and flag Lane A sensor channel for post-flight calibration.",
        "emergency_checklist": [
            "Step 1: Cross-check barometric reference against altimeter pressure setting.",
            "Step 2: Force primary FADEC control to Lane B.",
            "Step 3: Confirm engine operation stability."
        ],
        "maintenance_order": "Connect BRP BUDS diagnostic tool to ECU and recalibrate internal MAP transducer channel."
    }
}


class DiagnosticAgent:
    """
    Air-gapped Cognitive Diagnostic Reasoner (Plane 2).
    Enriches real-time diagnostic events with authoritative ATA-grounded maintenance manual
    citations, prescriptive pilot checklists, and structural reasonings without external dependencies.
    """

    def __init__(self, **kwargs):
        self.directives = ROTAX_ATA_FAULT_DIRECTIVES

    @staticmethod
    def _retarget_cylinder(text: str, template_cyl: int, actual_cyl: int) -> str:
        """Rewrite `#<template_cyl>` cylinder references to the cylinder actually implicated.

        The directive prose is authored around one example cylinder (e.g. fault 3 reads
        "drops EGT #2"). Injecting that fault on cylinder 3 used to emit the template's
        number verbatim, so the explanation contradicted the telemetry beside it. Only
        `#N` forms are substituted, which leaves checklist ordinals ("Step 1:") and
        specification figures ("4.5-5.5 kOhm") untouched.
        """
        return re.sub(rf"#\s*{template_cyl}\b", f"#{actual_cyl}", text)

    def diagnose(self, fault_id: int, confidence: float = 0.95,
                 trigger_residuals: Optional[Dict[str, Any]] = None,
                 cylinder: Optional[int] = None) -> DiagnosticDirective:
        """
        Generate an ATA-grounded diagnostic directive for a given fault.

        Args:
            fault_id: DRDO canonical fault ID (1..8).
            confidence: ML classification confidence from Plane 1.
            trigger_residuals: Real-time sensor residuals triggering the event.
            cylinder: 1-based cylinder the live evidence points at. For directives whose
                prose is cylinder-specific, every `#N` reference is retargeted to it.

        Returns:
            DiagnosticDirective with full OEM manual citations, causal chain, and step-by-step checklist.
        """
        data = self.directives.get(fault_id)

        if not data:
            # Fallback for unknown or unindexed anomalies
            return DiagnosticDirective(
                fault_id=fault_id,
                fault_name="NOMINAL_FLIGHT" if fault_id == 0 else "UNKNOWN_ANOMALY",
                ata_chapter="ATA 00-00",
                manual_reference="Rotax 912 iS Standard Maintenance Practices",
                subsystem="PROPULSION_CORE",
                target_3d_mesh="All",
                severity="NORMAL" if fault_id == 0 else "WARNING",
                root_cause_explanation="All 27 propulsion parameters operating within certified envelope." if fault_id == 0 else "Uncorrelated multi-channel parameter deviation detected outside nominal envelope.",
                causal_chain=[
                    "All 27 telemetry channels within FAA/EASA certified limits.",
                    "Continuous physics residual autoencoder loss < 0.05.",
                    "Zero sub-threshold sensor drift detected across fleet.",
                    "Subsystem health index nominal at 100.0%."
                ] if fault_id == 0 else [
                    "Anomalous variance detected outside baseline envelope.",
                    "Multi-sensor residual cross-correlation triggered warning.",
                    "Subsystem health reduced accordingly."
                ],
                prescriptive_action="Maintain standard flight profile (Ladakh FL200)." if fault_id == 0 else "Initiate precautionary engine telemetry monitoring.",
                emergency_checklist=[] if fault_id == 0 else [
                    "Step 1: Check primary flight and engine instruments.",
                    "Step 2: Note altitude, airspeed, and throttle setting.",
                    "Step 3: If deviations expand, reduce power and vector toward alternate landing site."
                ],
                maintenance_order="No maintenance required." if fault_id == 0 else "Perform general line maintenance inspection upon landing.",
                confidence=confidence,
                relevance_score=1.0 if fault_id == 0 else 0.5,
            )

        # Contextual explanation synthesizing authoritative data with live sensor residuals
        residual_summary = ""
        if trigger_residuals:
            items = []
            for ch, info in trigger_residuals.items():
                if isinstance(info, dict) and "residual" in info:
                    items.append(f"{ch} residual: {info['residual']:+.2f} {info.get('unit', '')}")
            if items:
                residual_summary = f" Active trigger residuals: [{'; '.join(items)}]."

        explanation = f"{data['root_cause_explanation']}{residual_summary}"

        # Retarget cylinder-specific prose onto the cylinder the live evidence implicates.
        # Engine-level directives carry no template_cylinder and pass through unchanged.
        template_cyl = data.get("template_cylinder")
        resolved_cyl = cylinder if (template_cyl and cylinder) else template_cyl
        if template_cyl and cylinder and cylinder != template_cyl:
            retarget = lambda s: self._retarget_cylinder(s, template_cyl, cylinder)
        else:
            retarget = lambda s: s

        return DiagnosticDirective(
            fault_id=fault_id,
            fault_name=retarget(data["fault_name"]),
            ata_chapter=data["ata_chapter"],
            manual_reference=data["manual_reference"],
            subsystem=data["subsystem"],
            target_3d_mesh=data["target_3d_mesh"],
            severity=data["severity"],
            root_cause_explanation=retarget(explanation),
            causal_chain=[retarget(step) for step in data.get("causal_chain", [])],
            prescriptive_action=retarget(data["prescriptive_action"]),
            emergency_checklist=[retarget(step) for step in data["emergency_checklist"]],
            maintenance_order=retarget(data["maintenance_order"]),
            confidence=confidence,
            relevance_score=1.0,
            cylinder=resolved_cyl,
        )
